# Generated by Django 5.2.17 on 2026-08-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
